In [1]:
"""
Cordell Newmiller
Prof. Fassnacht
PHY 266
Homework 2
Problem 2

In this problem, you are going to see how quickly a Poisson distribution converges to a Gaussian,
especially in the wings of the distribution. Use python’s random number generator to create five
data sets with 10,000 members each. The data in the five samples should be drawn from Poisson
distributions with means of 3, 10, 30, 100, and 1000, respectively. As usual, submit all your code
for this problem.
"""

import numpy

# When debugging, it's useful to decrease the number of data points used N. 
# The problem calls for N=10000.
N=10000
Means = numpy.array([3, 10, 30, 100, 1000])

# This creates an array with N rows, and one column for each of the desired means. 
RandomDataSet =  numpy.random.poisson(Means,size=(N,Means.size))


"""
Part (a): For each of the data sets, calculate the percentage of points that are contained within the
µ ± nσ regions, where n = 1, 2, 3. Make a table, where the rows are “1 σ”, “2 σ”, and “3 σ” and
the columns are the [five] data sets.
"""

# This problem calls for analysis within 1, 2, and 3 sigmas
WithinHowManySigmas=3

# For Poisson distributions, the mean is equal to the varience
Sigmas=Means**(1/2)

# This table will record the number of values falling within the intervals
NumberWithinTable=numpy.zeros([WithinHowManySigmas,Means.size])


# For each row i, add up the number of elements that fall within the intervals
for i in range(1,WithinHowManySigmas+1):
    NumberWithinTable[i-1,:]=(numpy.sum(numpy.logical_and((
                    Means-i*Sigmas)<RandomDataSet, RandomDataSet<(Means+i*Sigmas)),axis=0))
    # We have to use Numpy's logical_and to compare arrays.
    # The comparison appears to me to be a dimension mismatch at first, 
    # but Python recognizes the intended operation and compares each row. 


PercentWithinTable=NumberWithinTable/N
print('Part (a), table of percentages: \n',PercentWithinTable)

"""
Part (b): Find the boundaries of the regions that contain 68%, 95.4%, and 99.7% of the data sets that
you generated. Compare these boundaries to those defined by the corresponding µ ± nσ regions.
"""
print('Part (b), boundaries')

# Sort each column
SortedDataSet=numpy.msort(RandomDataSet)

Percentages=numpy.array([.68,.954,.997])

# Initialize tables
LowerBounds=numpy.zeros([WithinHowManySigmas,Means.size])
UpperBounds=numpy.zeros([WithinHowManySigmas,Means.size])
TheoreticalLowerBounds=numpy.zeros([WithinHowManySigmas,Means.size])
TheoreticalUpperBounds=numpy.zeros([WithinHowManySigmas,Means.size])

# Fill tables
for i in range(1,WithinHowManySigmas+1):
    LowerBounds[i-1,:]= SortedDataSet[int(numpy.around(N*(1-Percentages[i-1]))/2),:]
    UpperBounds[i-1,:]= SortedDataSet[int(numpy.around(N*(1+Percentages[i-1]))/2),:]
    TheoreticalLowerBounds[i-1,:]=Means-i*Sigmas
    TheoreticalUpperBounds[i-1,:]=Means+i*Sigmas

# Clip out negative theoretical bounds
TheoreticalLowerBounds=TheoreticalLowerBounds.clip(min=0)

numpy.set_printoptions(suppress=True,precision=3) # Suppress scientific notation output
print('Actual lower bounds: \n',LowerBounds)
print('Theoretical lower bounds: \n',TheoreticalLowerBounds)
print('Actual upper bounds: \n',UpperBounds)
print('Theoretical upper bounds: \n',TheoreticalUpperBounds)

print('Percent differences of lower bounds \n',
      (LowerBounds.clip(min=.001)/TheoreticalLowerBounds.clip(min=.001) - 1)*100) 
      # Avoid dividing by 0
print('Percent differences of upper bounds \n',(UpperBounds/TheoreticalUpperBounds - 1)*100)

numpy.set_printoptions(suppress=False,precision=8) # Reset to default, useful when working in notebook

# End of problem 2

Part (a), table of percentages: 
 [[ 0.6162  0.7323  0.6809  0.6688  0.6812]
 [ 0.9632  0.9628  0.947   0.9477  0.9543]
 [ 0.9964  0.9972  0.9974  0.996   0.9978]]
Part (b), boundaries
Actual lower bounds: 
 [[   1.    7.   25.   90.  968.]
 [   0.    4.   20.   81.  937.]
 [   0.    2.   16.   71.  913.]]
Theoretical lower bounds: 
 [[   1.268    6.838   24.523   90.     968.377]
 [   0.       3.675   19.046   80.     936.754]
 [   0.       0.513   13.568   70.     905.132]]
Actual upper bounds: 
 [[    5.    13.    36.   110.  1031.]
 [    7.    17.    41.   121.  1064.]
 [    9.    20.    47.   133.  1093.]]
Theoretical upper bounds: 
 [[    4.732    13.162    35.477   110.     1031.623]
 [    6.464    16.325    40.954   120.     1063.246]
 [    8.196    19.487    46.432   130.     1094.868]]
Percent differences of lower bounds 
 [[ -21.132    2.373    1.946    0.      -0.039]
 [   0.       8.83     5.011    1.25     0.026]
 [   0.     289.737   17.922    1.429    0.869]]
Percent di